version: "3.1"

services:
  mysql:
    image: mysql:8.0
    container_name: auction-pulse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: auction-pulse_db
      MYSQL_USER: auction-pulse_user
      MYSQL_PASSWORD: auction-pulse_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auction-pulse-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 30s

  redis:
    image: redis:7-alpine
    container_name: auction-pulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auction-pulse-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 30s
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: auction-pulse-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: auction-pulse
      RABBITMQ_DEFAULT_PASS: auction-pulse123
      RABBITMQ_DEFAULT_VHOST: auction-pulse_vhost
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - auction-pulse-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      timeout: 10s
      retries: 10
      interval: 30s

  mongo:
    image: mongo:6.0
    container_name: auction-pulse-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: auction-pulse_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - auction-pulse-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      timeout: 10s
      retries: 5
      interval: 30s

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  auction-pulse-network:
    driver: bridge
